
module.exports = {

    EXTENSION_ID: 'textmarker',

    EXTENSION_NAME: 'TextMarker',

    Event: {
        EXTENSION_READY: 'TEXT_MARKER_READY',
        TOGGLED_CASE_SENSITIVITY: 'TOGGLED_CASE_SENSITIVITY',
        MATCHING_MODE_INITIALISED: 'MATCHING_MODE_INITIALISED'
    }

};
